import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import LenisProvider from "./LenisProvider";


const rajdhani = Rajdhani({ weight: ["600", "700"], subsets: ["latin"], variable: "--font-rajdhani" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rajdhani.variable}`}>
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
